// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Action    string             `json:"action"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserStat struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	EventCount  int64              `json:"event_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
