// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateUserStats(ctx context.Context, arg CreateUserStatsParams) ([]UserStat, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListUserStats(ctx context.Context, arg ListUserStatsParams) ([]UserStat, error)
}

var _ Querier = (*Queries)(nil)
