// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserStats = `-- name: CreateUserStats :many
INSERT INTO user_stats (user_id, period_start, period_end, event_count)
SELECT
    user_id,
    $1::timestamptz,
    $2::timestamptz,
    COUNT(*)::bigint AS event_count
FROM events
WHERE created_at >= $1 AND created_at < $2
GROUP BY user_id
ON CONFLICT (user_id, period_start, period_end)
DO UPDATE SET event_count = EXCLUDED.event_count
RETURNING id, user_id, period_start, period_end, event_count, created_at
`

type CreateUserStatsParams struct {
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

func (q *Queries) CreateUserStats(ctx context.Context, arg CreateUserStatsParams) ([]UserStat, error) {
	rows, err := q.db.Query(ctx, createUserStats, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserStat
	for rows.Next() {
		var i UserStat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.EventCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserStats = `-- name: ListUserStats :many
SELECT id, user_id, period_start, period_end, event_count, created_at FROM user_stats
WHERE user_id = $1
  AND period_start >= $2
  AND period_end <= $3
ORDER BY period_start DESC
`

type ListUserStatsParams struct {
	UserID      int64              `json:"user_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

func (q *Queries) ListUserStats(ctx context.Context, arg ListUserStatsParams) ([]UserStat, error) {
	rows, err := q.db.Query(ctx, listUserStats, arg.UserID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserStat
	for rows.Next() {
		var i UserStat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.EventCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
